# Generated by Django 5.2.5 on 2025-08-25 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField()),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('race_ethnicity', models.CharField(max_length=20)),
                ('parental_level_of_education', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=20)),
                ('test_preparation_course', models.CharField(max_length=20)),
                ('reading_score', models.IntegerField()),
                ('writing_score', models.IntegerField()),
                ('predicted_math_score', models.FloatField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='app.batchprediction')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('race_ethnicity', models.CharField(max_length=20)),
                ('parental_level_of_education', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=20)),
                ('test_preparation_course', models.CharField(max_length=20)),
                ('reading_score', models.IntegerField()),
                ('writing_score', models.IntegerField()),
                ('predicted_math_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
